### ISSUE TITLE
Filename invalid if (file_len > DATA_BUF_SIZE - 1)

### ISSUE THREAD

**Issue by kschwi** [Wiznet/WIZ550web#15]
The modification labled "// ## 20141219 Eric added...", in httpServer.c 358 to 365 must be moved before the line 352. Currently fliles shorter than DATA_BUF_SIZE are opened with an empty filename.
Cheers
Knut

**Comment by OpusK** [comment]
First, there is a reason to store uri in a separate structure for data larger than the buffer size.

When a request comes from a client in the idle state, it responds immediately.
That is, for a response that does not exceed the buffer size, the response state is completed by that processing.

On the other hand, for responses that exceed the buffer size, you must send them multiple times.
For this reason, the module is to save the uri that was being sent to a special structure to remember. 
(That's why wrote the code ///// )

Best regard,
Kei.
